/**
 * Database connection.
 *
 * One schema, two drivers. In production DATABASE_URL points at a real
 * Postgres. In development it is empty and we run PGlite, which is Postgres
 * itself compiled to WebAssembly: same SQL, same migrations, same Drizzle
 * queries, but no install and no Docker. That matters because the machine this
 * is being built on has no Docker, and because a contributor should be able to
 * clone and run without provisioning anything.
 *
 * The two driver types differ only in their constructor. Every query below the
 * edge is identical, so we expose a single `Database` type and let the rest of
 * the codebase stay driver-agnostic.
 */

import { mkdirSync } from 'node:fs';

import { PGlite } from '@electric-sql/pglite';
import { drizzle as drizzlePglite } from 'drizzle-orm/pglite';
import { drizzle as drizzleNode } from 'drizzle-orm/node-postgres';
import type { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';

import { config, isUsingPglite } from '../config.js';
import * as schema from './schema.js';

export type Database = NodePgDatabase<typeof schema>;

let db: Database | null = null;
let pglite: PGlite | null = null;
let pool: Pool | null = null;

export async function initDatabase(): Promise<Database> {
  if (db) return db;

  if (isUsingPglite()) {
    mkdirSync(config.pgliteDir, { recursive: true });
    pglite = new PGlite(config.pgliteDir);
    await pglite.waitReady;
    // The two drizzle constructors produce structurally identical query
    // builders; the cast keeps one Database type across the codebase.
    db = drizzlePglite(pglite, { schema }) as unknown as Database;
  } else {
    pool = new Pool({
      connectionString: config.databaseUrl,
      max: 10,
      idleTimeoutMillis: 30_000,
      // The droplet talks to Postgres over the Docker network, not the
      // internet, so TLS here would be ceremony. A managed database would
      // need this set to true.
      ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: true } : undefined,
    });
    await pool.query('select 1');
    db = drizzleNode(pool, { schema });
  }

  return db;
}

export function getDb(): Database {
  if (!db) throw new Error('Database used before initDatabase() was awaited.');
  return db;
}

/**
 * Apply pending migrations.
 *
 * Runs at boot in every environment. Migrations are generated by drizzle-kit
 * from `schema.ts` and committed, so the SQL that runs on the droplet is the
 * exact SQL that ran on the dev box, not something regenerated in place.
 */
export async function runMigrations(migrationsFolder: string): Promise<void> {
  if (pglite) {
    const { migrate } = await import('drizzle-orm/pglite/migrator');
    const pgliteDb = drizzlePglite(pglite, { schema });
    await migrate(pgliteDb, { migrationsFolder });
    return;
  }
  if (pool) {
    const { migrate } = await import('drizzle-orm/node-postgres/migrator');
    const nodeDb = drizzleNode(pool, { schema });
    await migrate(nodeDb, { migrationsFolder });
    return;
  }
  throw new Error('No database connection.');
}

/** Raw SQL escape hatch, used only by the migrator. */
export async function executeRaw(sql: string): Promise<void> {
  if (pglite) {
    await pglite.exec(sql);
    return;
  }
  if (pool) {
    await pool.query(sql);
    return;
  }
  throw new Error('No database connection.');
}

export async function closeDatabase(): Promise<void> {
  if (pglite) {
    await pglite.close();
    pglite = null;
  }
  if (pool) {
    await pool.end();
    pool = null;
  }
  db = null;
}

export { schema };
