/**
 * Working out who is actually on the other end of a request.
 *
 * The app listens on localhost behind nginx, so the socket address is always
 * nginx and the real visitor arrives in `X-Forwarded-For`. That header is a
 * list, and only one end of it can be believed.
 *
 * Each proxy *appends* the address it saw. So the right-hand end was written
 * by our own nginx from the TCP connection itself, and the left-hand end is
 * whatever the visitor chose to send. Reading the first entry, which is what
 * this used to do and what most tutorials do, hands the visitor a text box for
 * their own IP address: every login attempt can claim to come from somewhere
 * new, and the rate limit never fires.
 *
 * So we read from the right, and skip the entries that are our own plumbing.
 * bonesdeploy runs two nginx layers joined by a unix socket, which shows up in
 * the list as the literal text `unix:`; a loopback hop would show up as
 * 127.0.0.1. Neither is a visitor. The first real address from the right is
 * the one nginx saw on the wire, and nothing the visitor sends can move it.
 *
 * This holds whether nginx appends or overwrites, which matters because the
 * nginx config is generated by a tool and could be regenerated under us.
 */

import { isIP } from 'node:net';

function isLoopback(address: string): boolean {
  return address === '::1' || address.startsWith('127.') || address.startsWith('::ffff:127.');
}

/**
 * @param forwarded     the raw X-Forwarded-For header, if any
 * @param socketAddress the address of the TCP peer, which in production is nginx
 */
export function pickClientIp(
  forwarded: string | string[] | undefined,
  socketAddress: string | undefined,
): string {
  const peer = socketAddress ?? '';

  // Only a proxy on this machine gets to tell us who the visitor is. If the
  // peer is anything else, the port has been exposed by mistake and the header
  // is just something a stranger typed.
  const peerIsLocal = peer === '' || isLoopback(peer);
  if (!peerIsLocal) return peer;

  const header = Array.isArray(forwarded) ? forwarded.join(',') : (forwarded ?? '');
  const entries = header.split(',').map((entry) => entry.trim());

  for (let index = entries.length - 1; index >= 0; index -= 1) {
    const entry = entries[index]!;
    if (isIP(entry) === 0) continue;
    if (isLoopback(entry)) continue;
    return entry;
  }

  return peer || 'unknown';
}
