#!/usr/bin/env bash
# ONE TIME ONLY. Turns the empty block volume into the encrypted vault.
#
# It asks for a passphrase. That passphrase is generated by, and lives only in,
# the password manager on Wes's own machine. It is never written to this box:
# not in a file, not in a command argument, not in shell history. cryptsetup
# reads it straight from the terminal.
#
# DESTROYS whatever is on the volume. Refuses if the volume already holds a
# LUKS header or a filesystem, because the only time that is true is the time
# running this again would be a catastrophe.

source "$(dirname "$0")/lib.sh"
need_root

if ! command -v cryptsetup >/dev/null; then
  say "Installing cryptsetup"
  apt-get update -q
  apt-get install -y -q cryptsetup
fi

volume="$(find_volume)"
say "Volume: $volume -> $(readlink -f "$volume")"

if cryptsetup isLuks "$volume"; then
  die "this volume is ALREADY a LUKS vault. Use scryproof-unlock. If you truly mean to destroy it, wipe it by hand: wipefs -a $volume"
fi
existing="$(blkid -o value -s TYPE "$volume" 2>/dev/null || true)"
if [ -n "$existing" ]; then
  die "this volume already has a filesystem on it ($existing). It was probably created with automatic formatting. Wipe it by hand: wipefs -a $volume"
fi

say "Encrypting. Type the vault passphrase from the password manager, twice."
# LUKS2 defaults are what we want: AES-XTS-512 and argon2id key derivation.
# --iter-time 4000: four seconds of key stretching per guess, paid once per unlock.
# --pbkdf-memory 262144: argon2id's memory cost is written into the header and
# every unlock must find that much free. The default takes half the machine,
# which on a 1 GB box with swap off is an unlock that can be killed for memory.
# 256 MB is safe here, and the passphrase is seven random words either way.
cryptsetup luksFormat --type luks2 --iter-time 4000 --pbkdf-memory 262144 --label scryproof-vault "$volume"

say "Opening it. Type the passphrase once more."
cryptsetup open "$volume" "$VAULT_NAME"

say "Creating the filesystem"
mkfs.ext4 -q -L scryproof-vault "/dev/mapper/$VAULT_NAME"

say "Registering the mount point"
mkdir -p "$VAULT_MOUNT" "$STATE_DIR"
chmod 700 "$VAULT_MOUNT"
# noauto: never mounted at boot. nofail: boot does not wait for it.
# The short device timeout makes a gated service fail in seconds, not minutes.
if ! grep -q "[[:space:]]$VAULT_MOUNT[[:space:]]" /etc/fstab; then
  printf '/dev/mapper/%s %s ext4 noauto,nofail,noatime,x-systemd.device-timeout=10s 0 0\n' \
    "$VAULT_NAME" "$VAULT_MOUNT" >> /etc/fstab
fi
systemctl daemon-reload
mount "$VAULT_MOUNT"
# Again, after mounting: the chmod above was on the empty mount point, and the
# new filesystem's own root arrives world-readable.
chmod 700 "$VAULT_MOUNT"
mkdir -p "$VAULT_MOUNT/binds" "$VAULT_MOUNT/logs"
chmod 700 "$VAULT_MOUNT/binds"
touch "$BINDS_FILE" "$UNITS_FILE"

say "Header backup"
note "A damaged LUKS header means the data is gone even with the passphrase."
note "Copy the file below OFF this box, then delete it here:"
cryptsetup luksHeaderBackup "$volume" --header-backup-file /root/scryproof-vault-header.img
note "/root/scryproof-vault-header.img"
note "It is useless without the passphrase."

say "Done. The vault is open and mounted at $VAULT_MOUNT."
