/**
 * File storage.
 *
 * Two drivers behind one interface. Local disk for development and for a small
 * single-box deployment; S3-compatible for MinIO on the droplet. Note what is
 * *not* here: no third-party upload service ever holds our files, and files
 * are addressed by an opaque storage key rather than a public URL, so moving
 * hosts changes one config value and nothing else.
 */

import { createHash, randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, stat, unlink } from 'node:fs/promises';
import { dirname, extname, normalize, resolve, sep } from 'node:path';
import { pipeline } from 'node:stream/promises';
import type { Readable } from 'node:stream';

import { config } from '../config.js';
import { badRequest } from '../lib/http-error.js';

export interface StoredFile {
  key: string;
  size: number;
}

/**
 * Filenames arrive from users, so the stored key is generated by us and the
 * original name is kept only as metadata in the database. That removes path
 * traversal, encoding tricks and collisions in one move.
 */
export function buildStorageKey(originalName: string): string {
  const ext = extname(originalName).toLowerCase().slice(0, 12).replace(/[^a-z0-9.]/g, '');
  const id = randomUUID();
  // Shard by the first two characters so one directory never holds a million
  // files, which matters on the local driver.
  return `${id.slice(0, 2)}/${id}${ext}`;
}

function localPathFor(key: string): string {
  const root = resolve(config.storage.localPath);
  const target = resolve(root, normalize(key));
  // Defence in depth: keys are generated by us, but a bug elsewhere must not
  // become an arbitrary filesystem write.
  if (target !== root && !target.startsWith(root + sep)) {
    throw badRequest('Invalid storage key.', 'invalid_key');
  }
  return target;
}

export async function saveStream(key: string, input: Readable): Promise<StoredFile> {
  if (config.storage.driver === 's3') {
    return saveToS3(key, input);
  }

  const target = localPathFor(key);
  await mkdir(dirname(target), { recursive: true });
  await pipeline(input, createWriteStream(target));
  const info = await stat(target);
  return { key, size: info.size };
}

export function readStream(key: string): Readable {
  if (config.storage.driver === 's3') {
    throw new Error('S3 reads are served by presigned URLs, not by this process.');
  }
  return createReadStream(localPathFor(key));
}

export async function deleteObject(key: string): Promise<void> {
  if (config.storage.driver === 's3') {
    await deleteFromS3(key);
    return;
  }
  try {
    await unlink(localPathFor(key));
  } catch {
    // Already gone is the desired end state.
  }
}

/**
 * Attachment URLs point back at our own API rather than at the object store.
 * The request is permission-checked before the bytes are served, so a link
 * leaked out of a private channel is useless to someone who cannot read that
 * channel.
 */
export function publicUrlFor(attachmentId: string, filename: string): string {
  return `/api/attachments/${attachmentId}/${encodeURIComponent(filename)}`;
}

/* ------------------------------------------------------------------ *
 * S3-compatible driver (MinIO on the droplet).
 *
 * Written against the raw REST API with SigV4 rather than pulling in the AWS
 * SDK: it is roughly a hundred lines, it removes a large dependency tree from
 * a process that handles our most sensitive data, and it works unchanged
 * against MinIO, Backblaze B2 and DigitalOcean Spaces.
 * ------------------------------------------------------------------ */

async function signedFetch(
  method: 'PUT' | 'GET' | 'DELETE',
  key: string,
  body: Buffer | undefined,
): Promise<Response> {
  const { createHmac } = await import('node:crypto');
  const { endpoint, bucket, region, accessKeyId, secretAccessKey } = config.storage.s3;

  if (!endpoint || !accessKeyId || !secretAccessKey) {
    throw new Error('S3 storage is selected but S3_ENDPOINT / credentials are not configured.');
  }

  const url = new URL(`${endpoint.replace(/\/$/, '')}/${bucket}/${key}`);
  const now = new Date();
  const amzDate = now.toISOString().replace(/[:-]|\.\d{3}/g, '');
  const dateStamp = amzDate.slice(0, 8);

  const payloadHash = createHash('sha256')
    .update(body ?? Buffer.alloc(0))
    .digest('hex');

  const canonicalHeaders =
    `host:${url.host}\n` + `x-amz-content-sha256:${payloadHash}\n` + `x-amz-date:${amzDate}\n`;
  const signedHeaders = 'host;x-amz-content-sha256;x-amz-date';

  const canonicalRequest = [
    method,
    url.pathname,
    '',
    canonicalHeaders,
    signedHeaders,
    payloadHash,
  ].join('\n');

  const scope = `${dateStamp}/${region}/s3/aws4_request`;
  const stringToSign = [
    'AWS4-HMAC-SHA256',
    amzDate,
    scope,
    createHash('sha256').update(canonicalRequest).digest('hex'),
  ].join('\n');

  const sign = (k: Buffer | string, d: string): Buffer =>
    createHmac('sha256', k).update(d).digest();

  const signingKey = sign(sign(sign(sign(`AWS4${secretAccessKey}`, dateStamp), region), 's3'), 'aws4_request');
  const signature = createHmac('sha256', signingKey).update(stringToSign).digest('hex');

  const authorization =
    `AWS4-HMAC-SHA256 Credential=${accessKeyId}/${scope}, ` +
    `SignedHeaders=${signedHeaders}, Signature=${signature}`;

  return fetch(url, {
    method,
    headers: {
      Authorization: authorization,
      'x-amz-content-sha256': payloadHash,
      'x-amz-date': amzDate,
    },
    body,
  });
}

async function saveToS3(key: string, input: Readable): Promise<StoredFile> {
  const chunks: Buffer[] = [];
  for await (const chunk of input) chunks.push(Buffer.from(chunk as Buffer));
  const body = Buffer.concat(chunks);

  const response = await signedFetch('PUT', key, body);
  if (!response.ok) {
    throw new Error(`Object store rejected the upload: ${response.status} ${await response.text()}`);
  }
  return { key, size: body.length };
}

export async function readFromS3(key: string): Promise<Buffer> {
  const response = await signedFetch('GET', key, undefined);
  if (!response.ok) throw new Error(`Object store read failed: ${response.status}`);
  return Buffer.from(await response.arrayBuffer());
}

async function deleteFromS3(key: string): Promise<void> {
  await signedFetch('DELETE', key, undefined);
}

export async function ensureStorageReady(): Promise<void> {
  if (config.storage.driver === 'local') {
    await mkdir(config.storage.localPath, { recursive: true });
  }
}
