/**
 * The countries Travhole knows, and which touch which by land. Vendored
 * (nothing is fetched).
 *
 * From mledoze/countries (github.com/mledoze/countries), which is under the
 * Open Database License 1.0: independent countries, and Kosovo, Palestine,
 * Taiwan and Western Sahara, because a route across a map with holes in it
 * is a worse game. Territories are left out. Made by a script; a border can
 * be mended by hand here.
 */

export interface TravleCountry {
  /** Three letters, ISO where there is one. */
  code: string;
  name: string;
  /** Codes of the countries it touches by land. */
  borders: readonly string[];
}

export const TRAVLE_COUNTRIES: readonly TravleCountry[] = [
  { code: 'AFG', name: "Afghanistan", borders: ['CHN', 'IRN', 'PAK', 'TJK', 'TKM', 'UZB'] },
  { code: 'ALB', name: "Albania", borders: ['GRC', 'KOS', 'MKD', 'MNE'] },
  { code: 'DZA', name: "Algeria", borders: ['ESH', 'LBY', 'MAR', 'MLI', 'MRT', 'NER', 'TUN'] },
  { code: 'AND', name: "Andorra", borders: ['ESP', 'FRA'] },
  { code: 'AGO', name: "Angola", borders: ['COD', 'COG', 'NAM', 'ZMB'] },
  { code: 'ATG', name: "Antigua and Barbuda", borders: [] },
  { code: 'ARG', name: "Argentina", borders: ['BOL', 'BRA', 'CHL', 'PRY', 'URY'] },
  { code: 'ARM', name: "Armenia", borders: ['AZE', 'GEO', 'IRN', 'TUR'] },
  { code: 'AUS', name: "Australia", borders: [] },
  { code: 'AUT', name: "Austria", borders: ['CHE', 'CZE', 'DEU', 'HUN', 'ITA', 'LIE', 'SVK', 'SVN'] },
  { code: 'AZE', name: "Azerbaijan", borders: ['ARM', 'GEO', 'IRN', 'RUS', 'TUR'] },
  { code: 'BHS', name: "Bahamas", borders: [] },
  { code: 'BHR', name: "Bahrain", borders: [] },
  { code: 'BGD', name: "Bangladesh", borders: ['IND', 'MMR'] },
  { code: 'BRB', name: "Barbados", borders: [] },
  { code: 'BLR', name: "Belarus", borders: ['LTU', 'LVA', 'POL', 'RUS', 'UKR'] },
  { code: 'BEL', name: "Belgium", borders: ['DEU', 'FRA', 'LUX', 'NLD'] },
  { code: 'BLZ', name: "Belize", borders: ['GTM', 'MEX'] },
  { code: 'BEN', name: "Benin", borders: ['BFA', 'NER', 'NGA', 'TGO'] },
  { code: 'BTN', name: "Bhutan", borders: ['CHN', 'IND'] },
  { code: 'BOL', name: "Bolivia", borders: ['ARG', 'BRA', 'CHL', 'PER', 'PRY'] },
  { code: 'BIH', name: "Bosnia and Herzegovina", borders: ['HRV', 'MNE', 'SRB'] },
  { code: 'BWA', name: "Botswana", borders: ['NAM', 'ZAF', 'ZMB', 'ZWE'] },
  { code: 'BRA', name: "Brazil", borders: ['ARG', 'BOL', 'COL', 'GUY', 'PER', 'PRY', 'SUR', 'URY', 'VEN'] },
  { code: 'BRN', name: "Brunei", borders: ['MYS'] },
  { code: 'BGR', name: "Bulgaria", borders: ['GRC', 'MKD', 'ROU', 'SRB', 'TUR'] },
  { code: 'BFA', name: "Burkina Faso", borders: ['BEN', 'CIV', 'GHA', 'MLI', 'NER', 'TGO'] },
  { code: 'BDI', name: "Burundi", borders: ['COD', 'RWA', 'TZA'] },
  { code: 'KHM', name: "Cambodia", borders: ['LAO', 'THA', 'VNM'] },
  { code: 'CMR', name: "Cameroon", borders: ['CAF', 'COG', 'GAB', 'GNQ', 'NGA', 'TCD'] },
  { code: 'CAN', name: "Canada", borders: ['USA'] },
  { code: 'CPV', name: "Cape Verde", borders: [] },
  { code: 'CAF', name: "Central African Republic", borders: ['CMR', 'COD', 'COG', 'SDN', 'SSD', 'TCD'] },
  { code: 'TCD', name: "Chad", borders: ['CAF', 'CMR', 'LBY', 'NER', 'NGA', 'SDN'] },
  { code: 'CHL', name: "Chile", borders: ['ARG', 'BOL', 'PER'] },
  { code: 'CHN', name: "China", borders: ['AFG', 'BTN', 'IND', 'KAZ', 'KGZ', 'LAO', 'MMR', 'MNG', 'NPL', 'PAK', 'PRK', 'RUS', 'TJK', 'VNM'] },
  { code: 'COL', name: "Colombia", borders: ['BRA', 'ECU', 'PAN', 'PER', 'VEN'] },
  { code: 'COM', name: "Comoros", borders: [] },
  { code: 'COG', name: "Congo", borders: ['AGO', 'CAF', 'CMR', 'COD', 'GAB'] },
  { code: 'CRI', name: "Costa Rica", borders: ['NIC', 'PAN'] },
  { code: 'HRV', name: "Croatia", borders: ['BIH', 'HUN', 'MNE', 'SRB', 'SVN'] },
  { code: 'CUB', name: "Cuba", borders: [] },
  { code: 'CYP', name: "Cyprus", borders: [] },
  { code: 'CZE', name: "Czechia", borders: ['AUT', 'DEU', 'POL', 'SVK'] },
  { code: 'DNK', name: "Denmark", borders: ['DEU'] },
  { code: 'DJI', name: "Djibouti", borders: ['ERI', 'ETH', 'SOM'] },
  { code: 'DMA', name: "Dominica", borders: [] },
  { code: 'DOM', name: "Dominican Republic", borders: ['HTI'] },
  { code: 'COD', name: "DR Congo", borders: ['AGO', 'BDI', 'CAF', 'COG', 'RWA', 'SSD', 'TZA', 'UGA', 'ZMB'] },
  { code: 'ECU', name: "Ecuador", borders: ['COL', 'PER'] },
  { code: 'EGY', name: "Egypt", borders: ['ISR', 'LBY', 'PSE', 'SDN'] },
  { code: 'SLV', name: "El Salvador", borders: ['GTM', 'HND'] },
  { code: 'GNQ', name: "Equatorial Guinea", borders: ['CMR', 'GAB'] },
  { code: 'ERI', name: "Eritrea", borders: ['DJI', 'ETH', 'SDN'] },
  { code: 'EST', name: "Estonia", borders: ['LVA', 'RUS'] },
  { code: 'SWZ', name: "Eswatini", borders: ['MOZ', 'ZAF'] },
  { code: 'ETH', name: "Ethiopia", borders: ['DJI', 'ERI', 'KEN', 'SDN', 'SOM', 'SSD'] },
  { code: 'FJI', name: "Fiji", borders: [] },
  { code: 'FIN', name: "Finland", borders: ['NOR', 'RUS', 'SWE'] },
  { code: 'FRA', name: "France", borders: ['AND', 'BEL', 'CHE', 'DEU', 'ESP', 'ITA', 'LUX', 'MCO'] },
  { code: 'GAB', name: "Gabon", borders: ['CMR', 'COG', 'GNQ'] },
  { code: 'GMB', name: "Gambia", borders: ['SEN'] },
  { code: 'GEO', name: "Georgia", borders: ['ARM', 'AZE', 'RUS', 'TUR'] },
  { code: 'DEU', name: "Germany", borders: ['AUT', 'BEL', 'CHE', 'CZE', 'DNK', 'FRA', 'LUX', 'NLD', 'POL'] },
  { code: 'GHA', name: "Ghana", borders: ['BFA', 'CIV', 'TGO'] },
  { code: 'GRC', name: "Greece", borders: ['ALB', 'BGR', 'MKD', 'TUR'] },
  { code: 'GRD', name: "Grenada", borders: [] },
  { code: 'GTM', name: "Guatemala", borders: ['BLZ', 'HND', 'MEX', 'SLV'] },
  { code: 'GIN', name: "Guinea", borders: ['CIV', 'GNB', 'LBR', 'MLI', 'SEN', 'SLE'] },
  { code: 'GNB', name: "Guinea-Bissau", borders: ['GIN', 'SEN'] },
  { code: 'GUY', name: "Guyana", borders: ['BRA', 'SUR', 'VEN'] },
  { code: 'HTI', name: "Haiti", borders: ['DOM'] },
  { code: 'HND', name: "Honduras", borders: ['GTM', 'NIC', 'SLV'] },
  { code: 'HUN', name: "Hungary", borders: ['AUT', 'HRV', 'ROU', 'SRB', 'SVK', 'SVN', 'UKR'] },
  { code: 'ISL', name: "Iceland", borders: [] },
  { code: 'IND', name: "India", borders: ['BGD', 'BTN', 'CHN', 'MMR', 'NPL', 'PAK'] },
  { code: 'IDN', name: "Indonesia", borders: ['MYS', 'PNG', 'TLS'] },
  { code: 'IRN', name: "Iran", borders: ['AFG', 'ARM', 'AZE', 'IRQ', 'PAK', 'TKM', 'TUR'] },
  { code: 'IRQ', name: "Iraq", borders: ['IRN', 'JOR', 'KWT', 'SAU', 'SYR', 'TUR'] },
  { code: 'IRL', name: "Ireland", borders: ['GBR'] },
  { code: 'ISR', name: "Israel", borders: ['EGY', 'JOR', 'LBN', 'PSE', 'SYR'] },
  { code: 'ITA', name: "Italy", borders: ['AUT', 'CHE', 'FRA', 'SMR', 'SVN', 'VAT'] },
  { code: 'CIV', name: "Ivory Coast", borders: ['BFA', 'GHA', 'GIN', 'LBR', 'MLI'] },
  { code: 'JAM', name: "Jamaica", borders: [] },
  { code: 'JPN', name: "Japan", borders: [] },
  { code: 'JOR', name: "Jordan", borders: ['IRQ', 'ISR', 'PSE', 'SAU', 'SYR'] },
  { code: 'KAZ', name: "Kazakhstan", borders: ['CHN', 'KGZ', 'RUS', 'TKM', 'UZB'] },
  { code: 'KEN', name: "Kenya", borders: ['ETH', 'SOM', 'SSD', 'TZA', 'UGA'] },
  { code: 'KIR', name: "Kiribati", borders: [] },
  { code: 'KOS', name: "Kosovo", borders: ['ALB', 'MKD', 'MNE', 'SRB'] },
  { code: 'KWT', name: "Kuwait", borders: ['IRQ', 'SAU'] },
  { code: 'KGZ', name: "Kyrgyzstan", borders: ['CHN', 'KAZ', 'TJK', 'UZB'] },
  { code: 'LAO', name: "Laos", borders: ['CHN', 'KHM', 'MMR', 'THA', 'VNM'] },
  { code: 'LVA', name: "Latvia", borders: ['BLR', 'EST', 'LTU', 'RUS'] },
  { code: 'LBN', name: "Lebanon", borders: ['ISR', 'SYR'] },
  { code: 'LSO', name: "Lesotho", borders: ['ZAF'] },
  { code: 'LBR', name: "Liberia", borders: ['CIV', 'GIN', 'SLE'] },
  { code: 'LBY', name: "Libya", borders: ['DZA', 'EGY', 'NER', 'SDN', 'TCD', 'TUN'] },
  { code: 'LIE', name: "Liechtenstein", borders: ['AUT', 'CHE'] },
  { code: 'LTU', name: "Lithuania", borders: ['BLR', 'LVA', 'POL', 'RUS'] },
  { code: 'LUX', name: "Luxembourg", borders: ['BEL', 'DEU', 'FRA'] },
  { code: 'MDG', name: "Madagascar", borders: [] },
  { code: 'MWI', name: "Malawi", borders: ['MOZ', 'TZA', 'ZMB'] },
  { code: 'MYS', name: "Malaysia", borders: ['BRN', 'IDN', 'THA'] },
  { code: 'MDV', name: "Maldives", borders: [] },
  { code: 'MLI', name: "Mali", borders: ['BFA', 'CIV', 'DZA', 'GIN', 'MRT', 'NER', 'SEN'] },
  { code: 'MLT', name: "Malta", borders: [] },
  { code: 'MHL', name: "Marshall Islands", borders: [] },
  { code: 'MRT', name: "Mauritania", borders: ['DZA', 'ESH', 'MLI', 'SEN'] },
  { code: 'MUS', name: "Mauritius", borders: [] },
  { code: 'MEX', name: "Mexico", borders: ['BLZ', 'GTM', 'USA'] },
  { code: 'FSM', name: "Micronesia", borders: [] },
  { code: 'MDA', name: "Moldova", borders: ['ROU', 'UKR'] },
  { code: 'MCO', name: "Monaco", borders: ['FRA'] },
  { code: 'MNG', name: "Mongolia", borders: ['CHN', 'RUS'] },
  { code: 'MNE', name: "Montenegro", borders: ['ALB', 'BIH', 'HRV', 'KOS', 'SRB'] },
  { code: 'MAR', name: "Morocco", borders: ['DZA', 'ESH', 'ESP'] },
  { code: 'MOZ', name: "Mozambique", borders: ['MWI', 'SWZ', 'TZA', 'ZAF', 'ZMB', 'ZWE'] },
  { code: 'MMR', name: "Myanmar", borders: ['BGD', 'CHN', 'IND', 'LAO', 'THA'] },
  { code: 'NAM', name: "Namibia", borders: ['AGO', 'BWA', 'ZAF', 'ZMB'] },
  { code: 'NRU', name: "Nauru", borders: [] },
  { code: 'NPL', name: "Nepal", borders: ['CHN', 'IND'] },
  { code: 'NLD', name: "Netherlands", borders: ['BEL', 'DEU'] },
  { code: 'NZL', name: "New Zealand", borders: [] },
  { code: 'NIC', name: "Nicaragua", borders: ['CRI', 'HND'] },
  { code: 'NER', name: "Niger", borders: ['BEN', 'BFA', 'DZA', 'LBY', 'MLI', 'NGA', 'TCD'] },
  { code: 'NGA', name: "Nigeria", borders: ['BEN', 'CMR', 'NER', 'TCD'] },
  { code: 'PRK', name: "North Korea", borders: ['CHN', 'KOR', 'RUS'] },
  { code: 'MKD', name: "North Macedonia", borders: ['ALB', 'BGR', 'GRC', 'KOS', 'SRB'] },
  { code: 'NOR', name: "Norway", borders: ['FIN', 'RUS', 'SWE'] },
  { code: 'OMN', name: "Oman", borders: ['ARE', 'SAU', 'YEM'] },
  { code: 'PAK', name: "Pakistan", borders: ['AFG', 'CHN', 'IND', 'IRN'] },
  { code: 'PLW', name: "Palau", borders: [] },
  { code: 'PSE', name: "Palestine", borders: ['EGY', 'ISR', 'JOR'] },
  { code: 'PAN', name: "Panama", borders: ['COL', 'CRI'] },
  { code: 'PNG', name: "Papua New Guinea", borders: ['IDN'] },
  { code: 'PRY', name: "Paraguay", borders: ['ARG', 'BOL', 'BRA'] },
  { code: 'PER', name: "Peru", borders: ['BOL', 'BRA', 'CHL', 'COL', 'ECU'] },
  { code: 'PHL', name: "Philippines", borders: [] },
  { code: 'POL', name: "Poland", borders: ['BLR', 'CZE', 'DEU', 'LTU', 'RUS', 'SVK', 'UKR'] },
  { code: 'PRT', name: "Portugal", borders: ['ESP'] },
  { code: 'QAT', name: "Qatar", borders: ['SAU'] },
  { code: 'ROU', name: "Romania", borders: ['BGR', 'HUN', 'MDA', 'SRB', 'UKR'] },
  { code: 'RUS', name: "Russia", borders: ['AZE', 'BLR', 'CHN', 'EST', 'FIN', 'GEO', 'KAZ', 'LTU', 'LVA', 'MNG', 'NOR', 'POL', 'PRK', 'UKR'] },
  { code: 'RWA', name: "Rwanda", borders: ['BDI', 'COD', 'TZA', 'UGA'] },
  { code: 'KNA', name: "Saint Kitts and Nevis", borders: [] },
  { code: 'LCA', name: "Saint Lucia", borders: [] },
  { code: 'VCT', name: "Saint Vincent and the Grenadines", borders: [] },
  { code: 'WSM', name: "Samoa", borders: [] },
  { code: 'SMR', name: "San Marino", borders: ['ITA'] },
  { code: 'STP', name: "São Tomé and Príncipe", borders: [] },
  { code: 'SAU', name: "Saudi Arabia", borders: ['ARE', 'IRQ', 'JOR', 'KWT', 'OMN', 'QAT', 'YEM'] },
  { code: 'SEN', name: "Senegal", borders: ['GIN', 'GMB', 'GNB', 'MLI', 'MRT'] },
  { code: 'SRB', name: "Serbia", borders: ['BGR', 'BIH', 'HRV', 'HUN', 'KOS', 'MKD', 'MNE', 'ROU'] },
  { code: 'SYC', name: "Seychelles", borders: [] },
  { code: 'SLE', name: "Sierra Leone", borders: ['GIN', 'LBR'] },
  { code: 'SGP', name: "Singapore", borders: [] },
  { code: 'SVK', name: "Slovakia", borders: ['AUT', 'CZE', 'HUN', 'POL', 'UKR'] },
  { code: 'SVN', name: "Slovenia", borders: ['AUT', 'HRV', 'HUN', 'ITA'] },
  { code: 'SLB', name: "Solomon Islands", borders: [] },
  { code: 'SOM', name: "Somalia", borders: ['DJI', 'ETH', 'KEN'] },
  { code: 'ZAF', name: "South Africa", borders: ['BWA', 'LSO', 'MOZ', 'NAM', 'SWZ', 'ZWE'] },
  { code: 'KOR', name: "South Korea", borders: ['PRK'] },
  { code: 'SSD', name: "South Sudan", borders: ['CAF', 'COD', 'ETH', 'KEN', 'SDN', 'UGA'] },
  { code: 'ESP', name: "Spain", borders: ['AND', 'FRA', 'MAR', 'PRT'] },
  { code: 'LKA', name: "Sri Lanka", borders: [] },
  { code: 'SDN', name: "Sudan", borders: ['CAF', 'EGY', 'ERI', 'ETH', 'LBY', 'SSD', 'TCD'] },
  { code: 'SUR', name: "Suriname", borders: ['BRA', 'GUY'] },
  { code: 'SWE', name: "Sweden", borders: ['FIN', 'NOR'] },
  { code: 'CHE', name: "Switzerland", borders: ['AUT', 'DEU', 'FRA', 'ITA', 'LIE'] },
  { code: 'SYR', name: "Syria", borders: ['IRQ', 'ISR', 'JOR', 'LBN', 'TUR'] },
  { code: 'TWN', name: "Taiwan", borders: [] },
  { code: 'TJK', name: "Tajikistan", borders: ['AFG', 'CHN', 'KGZ', 'UZB'] },
  { code: 'TZA', name: "Tanzania", borders: ['BDI', 'COD', 'KEN', 'MOZ', 'MWI', 'RWA', 'UGA', 'ZMB'] },
  { code: 'THA', name: "Thailand", borders: ['KHM', 'LAO', 'MMR', 'MYS'] },
  { code: 'TLS', name: "Timor-Leste", borders: ['IDN'] },
  { code: 'TGO', name: "Togo", borders: ['BEN', 'BFA', 'GHA'] },
  { code: 'TON', name: "Tonga", borders: [] },
  { code: 'TTO', name: "Trinidad and Tobago", borders: [] },
  { code: 'TUN', name: "Tunisia", borders: ['DZA', 'LBY'] },
  { code: 'TUR', name: "Türkiye", borders: ['ARM', 'AZE', 'BGR', 'GEO', 'GRC', 'IRN', 'IRQ', 'SYR'] },
  { code: 'TKM', name: "Turkmenistan", borders: ['AFG', 'IRN', 'KAZ', 'UZB'] },
  { code: 'TUV', name: "Tuvalu", borders: [] },
  { code: 'UGA', name: "Uganda", borders: ['COD', 'KEN', 'RWA', 'SSD', 'TZA'] },
  { code: 'UKR', name: "Ukraine", borders: ['BLR', 'HUN', 'MDA', 'POL', 'ROU', 'RUS', 'SVK'] },
  { code: 'ARE', name: "United Arab Emirates", borders: ['OMN', 'SAU'] },
  { code: 'GBR', name: "United Kingdom", borders: ['IRL'] },
  { code: 'USA', name: "United States", borders: ['CAN', 'MEX'] },
  { code: 'URY', name: "Uruguay", borders: ['ARG', 'BRA'] },
  { code: 'UZB', name: "Uzbekistan", borders: ['AFG', 'KAZ', 'KGZ', 'TJK', 'TKM'] },
  { code: 'VUT', name: "Vanuatu", borders: [] },
  { code: 'VAT', name: "Vatican City", borders: ['ITA'] },
  { code: 'VEN', name: "Venezuela", borders: ['BRA', 'COL', 'GUY'] },
  { code: 'VNM', name: "Vietnam", borders: ['CHN', 'KHM', 'LAO'] },
  { code: 'ESH', name: "Western Sahara", borders: ['DZA', 'MAR', 'MRT'] },
  { code: 'YEM', name: "Yemen", borders: ['OMN', 'SAU'] },
  { code: 'ZMB', name: "Zambia", borders: ['AGO', 'BWA', 'COD', 'MOZ', 'MWI', 'NAM', 'TZA', 'ZWE'] },
  { code: 'ZWE', name: "Zimbabwe", borders: ['BWA', 'MOZ', 'ZAF', 'ZMB'] },
];
